version: '3.9'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./build:/var/www/web
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webpack
  webpack:
    image: node:latest
    volumes:
      - ./:/src
    working_dir: /src
    command: bash -c "npm install -g npm@latest && npm rebuild node-sass && npm install --legacy-peer-deps && npm run start"
    ports:
      - "3000:3000"

networks:
  default:
    name: api
    external: true
