version: '3.9'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./build:/var/www/web
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf/dev.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    name: api
    external: true
